name: tree_ranking
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=25.2
  - python=3.10
  - pyarrow
  - pandas
  - pyyaml
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.5.1+cu121
